### ISSUE TITLE
DECIDE Launch (2.4)

### ISSUE THREAD

**Issue by ztick** [gmm97/DD2480#7]
Please also include a file with proper parameters that pass, that fail and that are incorrect FOR THE WHOLE TEST.

The final launch/no launch decision is based on the FUV. The decision to launch requires that all elements in the FUV be true, i.e. LAUNCH should be set to true if and only if FUV[i] is true for all i, 0 ≤ i ≤ 14. For the example, LAUNCH is false because FUV[0] is false.

**Comment by jacobmimms** [comment]
I am just writing launch and providing unit test cases for the function. I think forming tests cases with all parameters should be another issue (if that is what was implied) , as it isn't related to just this function. I will simply test launch using a fuv that I create.
